/**
 * The OpenAPI document these routes produce, and its exact serialization.
 *
 * Two callers need it and they must agree byte for byte: `emit.ts` writes
 * `openapi.json`, and `contract.spec.ts` fails the build when the committed file
 * differs from what the routes emit right now. If each did its own
 * `JSON.stringify`, a difference in indentation or a missing trailing newline
 * would be a permanently red test that says the contract is stale when it is not.
 *
 * It also puts `app.swagger()` in the one project where `@fastify/swagger`'s type
 * augmentation is loaded. The spec project resolves `server.js` to its declaration
 * output, and a `.d.ts` does not carry the plugin import that adds `swagger()` to
 * `FastifyInstance` — so the call has to live here rather than in a spec.
 */

import { DEFAULT_API_PORT } from '../lib/config.js';
import { createContext } from '../lib/context.js';
import { buildServer } from '../lib/server.js';

/**
 * Build the document over a throwaway in-memory store.
 *
 * At build time and not against a running server, because "a client generated by
 * curling a running server can only be regenerated by someone who has one
 * running — and the schema would then describe whichever database happened to be
 * open." The document is a function of the route schemas alone, so this binds
 * nothing and opens a store it discards.
 */
export async function buildOpenapiDocument(): Promise<Record<string, unknown>> {
  const context = createContext({
    databaseFile: ':memory:',
    profilesDir: null,
  });
  const app = await buildServer({
    context,
    config: {
      port: DEFAULT_API_PORT,
      databaseFile: ':memory:',
      profilesDir: null,
      backupDir: '',
    },
  });

  const document = app.swagger() as Record<string, unknown>;

  await app.close();
  context.close();

  return document;
}

/** Exactly the bytes `openapi.json` holds — trailing newline included. */
export async function serializeOpenapiDocument(): Promise<string> {
  return `${JSON.stringify(await buildOpenapiDocument(), null, 2)}\n`;
}
