/**
 * Emit `openapi.json` at build time (§2.3).
 *
 * "OpenAPI schema emitted at build time and used to generate
 * `shared/api-client`." At *build* time and not at runtime, because a client
 * generated by curling a running server can only be regenerated by someone who
 * has one running — and the schema would then describe whichever database
 * happened to be open. The document is a function of the route schemas alone, so
 * this binds nothing and opens an in-memory store it throws away.
 *
 * The emitted file is committed. It is the API contract; a contract that only
 * exists in a build output cannot be reviewed in a diff.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_API_PORT } from '../lib/config.js';
import { createContext } from '../lib/context.js';
import { buildServer } from '../lib/server.js';

/** `dist/openapi/emit.js` and `src/openapi/emit.ts` are at equal depth, so this
 *  resolves to the app root from either. */
const appRoot = resolve(fileURLToPath(new URL('../..', import.meta.url)));

async function emit(): Promise<void> {
  const context = createContext({ databaseFile: ':memory:', profilesDir: null });
  const app = await buildServer({
    context,
    config: {
      port: DEFAULT_API_PORT,
      databaseFile: ':memory:',
      profilesDir: null,
      backupDir: '',
    },
  });

  const document = app.swagger();
  const target = resolve(appRoot, 'openapi.json');
  writeFileSync(target, `${JSON.stringify(document, null, 2)}\n`, 'utf8');

  await app.close();
  context.close();

  process.stdout.write(`openapi.json written to ${target}\n`);
}

emit().catch((error: unknown) => {
  process.stderr.write(`${(error as Error).stack ?? String(error)}\n`);
  process.exit(1);
});
