/**
 * Emit `openapi.json` at build time (§2.3).
 *
 * "OpenAPI schema emitted at build time and used to generate
 * `shared/api-client`." At *build* time and not at runtime, because a client
 * generated by curling a running server can only be regenerated by someone who
 * has one running — and the schema would then describe whichever database
 * happened to be open. The document is a function of the route schemas alone, so
 * building it binds nothing; see `document.ts`, which both this and
 * `contract.spec.ts` go through so the two cannot disagree about a newline.
 *
 * The emitted file is committed. It is the API contract; a contract that only
 * exists in a build output cannot be reviewed in a diff.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { serializeOpenapiDocument } from './document.js';

/** `dist/openapi/emit.js` and `src/openapi/emit.ts` are at equal depth, so this
 *  resolves to the app root from either. */
const appRoot = resolve(fileURLToPath(new URL('../..', import.meta.url)));

async function emit(): Promise<void> {
  const target = resolve(appRoot, 'openapi.json');
  writeFileSync(target, await serializeOpenapiDocument(), 'utf8');
  process.stdout.write(`openapi.json written to ${target}\n`);
}

emit().catch((error: unknown) => {
  process.stderr.write(`${(error as Error).stack ?? String(error)}\n`);
  process.exit(1);
});
