/**
 * The starter library, loaded once on first launch (meal-planner-spec.md §15).
 *
 * The content lives beside this lib in `seed/*.json`, generated by
 * `tools/make-meal-planner-seeds.mjs` (read its header for why a generator), and the app
 * build serves it at `assets/seed/`. Seeds are ordinary rows marked `source = 'seed'`:
 * the person edits or deletes them like anything else.
 *
 * Loaded at most once per seed version, recorded in `settings` — so deleting a seed meal
 * keeps it deleted instead of bringing it back on the next launch.
 */

import type { BaseUnit, SlotType } from '@metrum/meal-planner-domain';
import { MealsRepo } from './meals.js';
import { ProductsRepo } from './products.js';
import type { Clock, SqlDb } from './sql.js';

export interface SeedProduct {
  readonly key: string;
  readonly name: string;
  readonly packageUnit: BaseUnit;
  readonly packageAmount: number;
  readonly kcal: number;
  readonly proteinG: number;
}

export interface SeedMeal {
  readonly key: string;
  readonly name: string;
  readonly servings: number;
  readonly slots: readonly SlotType[];
  readonly ingredients: readonly { readonly product: string; readonly quantity: number; readonly displayText: string }[];
}

export interface SeedLibrary {
  readonly version: number;
  readonly products: readonly SeedProduct[];
  readonly meals: readonly SeedMeal[];
}

const SEED_KEY = 'seed_version';

/** Loads `seed` if this version has not been loaded before. True when it loaded. */
export async function loadSeedLibrary(db: SqlDb, clock: Clock, seed: SeedLibrary): Promise<boolean> {
  const rows = await db.all<{ value: string }>('SELECT value FROM settings WHERE key = ?', [SEED_KEY]);
  const loaded = rows[0] ? Number(JSON.parse(rows[0].value)) : 0;
  if (loaded >= seed.version) return false;

  const products = new ProductsRepo(db, clock);
  const meals = new MealsRepo(db, clock);
  await db.transaction(async (tx) => {
    const ids = new Map<string, { id: string; unit: BaseUnit }>();
    for (const p of seed.products) {
      const created = await products.create(
        {
          barcode: null,
          name: p.name,
          brand: null,
          packageUnit: p.packageUnit,
          packageAmount: p.packageAmount,
          kcal: p.kcal,
          proteinG: p.proteinG,
          source: 'seed',
        },
        tx,
      );
      ids.set(p.key, { id: created.id, unit: p.packageUnit });
    }
    for (const m of seed.meals) {
      await meals.create(
        {
          name: m.name,
          servings: m.servings,
          slots: m.slots,
          source: 'seed',
          sourceUrl: null,
          ingredients: m.ingredients.map((line) => {
            const product = ids.get(line.product);
            if (!product) throw new Error(`seed meal ${m.key} uses unknown product ${line.product}`);
            return { productId: product.id, quantity: line.quantity, unit: product.unit, displayText: line.displayText, toTaste: false };
          }),
        },
        tx,
      );
    }
    await tx.run('INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value', [
      SEED_KEY,
      JSON.stringify(seed.version),
    ]);
  });
  return true;
}
